version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-gpt-bot
    volumes:
      - ./config.ini:/app/config.ini:ro
    ports:
      - "8080:8080"
    restart: unless-stopped